import { 
  User, 
  Investor, 
  FarmSector, 
  Investment, 
  IncomeRecord, 
  ExpenseRecord, 
  FarmOperationRecord, 
  InventoryItem, 
  AssetItem, 
  DocumentRecord, 
  ProfitDistribution, 
  AuditLog, 
  CustomModule, 
  DashboardWidgetConfig, 
  Announcement, 
  GalleryItem, 
  FarmSettings 
} from '../types';
import { APP_IMAGES } from '../utils/imageAssets';

export const initialUsers: User[] = [
  {
    id: 'user-admin',
    name: 'Engr. Kazi Tariqul Islam',
    nameBn: 'প্রকৌশলী কাজী তরিকুল ইসলাম',
    email: 'admin@ahmadunagro.com',
    phone: '+8801711000111',
    role: 'super_admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 'user-accountant',
    name: 'Md. Mizanur Rahman, FCA',
    nameBn: 'মোঃ মিজানুর রহমান, এফসিএ',
    email: 'accounts@ahmadunagro.com',
    phone: '+8801819222333',
    role: 'accountant',
  },
  {
    id: 'user-mgr-duck',
    name: 'Md. Jahangir Alam',
    nameBn: 'মোঃ জাহাঙ্গীর আলম (হাঁস খামার)',
    email: 'jahangir.duck@ahmadunagro.com',
    phone: '+8801912333444',
    role: 'sector_manager',
    assignedSectorId: 'sec-duck',
  },
  {
    id: 'user-mgr-goat',
    name: 'Abul Kashem',
    nameBn: 'আবুল কাশেম (ছাগল খামার)',
    email: 'kashem.goat@ahmadunagro.com',
    phone: '+8801715444555',
    role: 'sector_manager',
    assignedSectorId: 'sec-goat',
  },
  {
    id: 'user-inv-1',
    name: 'Kazi Rafiqul Islam',
    nameBn: 'কাজী রফিকুল ইসলাম',
    email: 'rafiqul.investor@gmail.com',
    phone: '+8801712555666',
    role: 'investor',
    investorProfileId: 'inv-1',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
  },
  {
    id: 'user-inv-2',
    name: 'Begum Farzana Ahmed',
    nameBn: 'বেগম ফারজানা আহমেদ',
    email: 'farzana.ahmed.uk@gmail.com',
    phone: '+8801817888999',
    role: 'investor',
    investorProfileId: 'inv-2',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
  },
];

export const initialInvestors: Investor[] = [
  {
    id: 'inv-1',
    userId: 'user-inv-1',
    name: 'Kazi Rafiqul Islam',
    nameBn: 'কাজী রফিকুল ইসলাম',
    nid: '19842691234567890',
    phone: '+8801712555666',
    email: 'rafiqul.investor@gmail.com',
    address: 'House #45, Road #11, Sector #4, Uttara, Dhaka-1230',
    nationality: 'Bangladeshi',
    joiningDate: '2025-01-10',
    bankDetails: {
      bankName: 'Islami Bank Bangladesh PLC',
      branchName: 'Uttara Branch, Dhaka',
      accountName: 'Kazi Rafiqul Islam',
      accountNumber: '20501234567890',
      routingNumber: '125271234',
      bkashNumber: '01712555666',
      nagadNumber: '01712555666',
    },
    status: 'active',
    notes: 'Multi-sector verified investor. Invested in Duck and Goat Farming.',
  },
  {
    id: 'inv-2',
    userId: 'user-inv-2',
    name: 'Begum Farzana Ahmed',
    nameBn: 'বেগম ফারজানা আহমেদ',
    nid: '19902699876543210',
    phone: '+8801817888999',
    email: 'farzana.ahmed.uk@gmail.com',
    address: 'Flat 5B, Road 18, Block G, Banani, Dhaka / London, UK',
    nationality: 'Bangladeshi (Expatriate NRB)',
    joiningDate: '2025-03-15',
    bankDetails: {
      bankName: 'Standard Chartered Bank Bangladesh',
      branchName: 'Gulshan Branch',
      accountName: 'Farzana Ahmed',
      accountNumber: '01123456789',
      routingNumber: '215261111',
      bkashNumber: '01817888999',
    },
    status: 'active',
    notes: 'Invested in high-tech organic vegetable greenhouse & drip irrigation project.',
  },
  {
    id: 'inv-3',
    userId: 'user-inv-3',
    name: 'Dr. Mahmud Hasan',
    nameBn: 'ডাঃ মাহমুদ হাসান',
    nid: '19792611223344556',
    phone: '+8801911444555',
    email: 'mahmud.hasan.doctor@gmail.com',
    address: 'Medical College Road, Nasirabad, Chattogram',
    nationality: 'Bangladeshi',
    joiningDate: '2025-05-01',
    bankDetails: {
      bankName: 'City Bank PLC',
      branchName: 'Agrabad Branch',
      accountName: 'Dr. Mahmud Hasan',
      accountNumber: '1102987654321',
      routingNumber: '085270011',
      bkashNumber: '01911444555',
    },
    status: 'active',
    notes: 'Invested in Layer & Broiler Poultry sector.',
  },
  {
    id: 'inv-4',
    userId: 'user-inv-4',
    name: 'Tanvir Hossain',
    nameBn: 'তানভীর হোসেন',
    nid: '19952677889900112',
    phone: '+8801611777888',
    email: 'tanvir.agro@gmail.com',
    address: 'Uposhohor, Rajshahi',
    nationality: 'Bangladeshi',
    joiningDate: '2025-06-20',
    bankDetails: {
      bankName: 'Brac Bank PLC',
      branchName: 'Rajshahi Branch',
      accountName: 'Tanvir Hossain',
      accountNumber: '1501203948576',
      bkashNumber: '01611777888',
      nagadNumber: '01611777888',
    },
    status: 'active',
    notes: 'Invested in fancy and commercial pigeon farming project.',
  },
];

export const initialSectors: FarmSector[] = [
  {
    id: 'sec-duck',
    code: 'DUCK-01',
    name: 'Duck Farming',
    nameBn: 'হাঁস খামার প্রকল্প',
    description: 'High-yield Khaki Campbell & Beijing duck farming with bio-secure open water pond channels and organic egg production in Kishoreganj Haor.',
    descriptionBn: 'কিশোরগঞ্জ হাওর অঞ্চলে খাকি ক্যাম্পবেল ও বেইজিং হাঁসের মুক্ত জলাশয় ভিত্তিক আধুনিক ডিম ও মাংস উৎপাদন প্রকল্প।',
    image: APP_IMAGES.sectorDuck,
    managerUserId: 'user-mgr-duck',
    managerName: 'Md. Jahangir Alam',
    status: 'active',
    establishedDate: '2024-11-01',
    totalArea: '12 Bighas / ৪ একর',
    customMetrics: [
      { label: 'Total Ducks', labelBn: 'মোট হাঁসের সংখ্যা', value: 3850, unit: 'Birds / টি' },
      { label: 'Laying Ducks', labelBn: 'ডিমপাড়া হাঁস', value: 3100, unit: 'Birds / টি' },
      { label: 'Daily Eggs Produced', labelBn: 'দৈনিক ডিম উৎপাদন', value: 2750, unit: 'Eggs / টি' },
      { label: 'Current Mortality', labelBn: 'মাসিক মৃত্যুহার', value: 12, unit: 'Birds / টি' },
    ],
  },
  {
    id: 'sec-poultry',
    code: 'POULTRY-02',
    name: 'Chicken/Poultry Farming',
    nameBn: 'পোল্ট্রি ও মুরগি খামার',
    description: 'Automated climate-controlled commercial layer and Sonali chicken shed in Gazipur producing certified fresh eggs and organic poultry.',
    descriptionBn: 'গাজীপুরে উন্নত সোনালীর ও লেয়ার মুরগির অটোমেটেড শেড, বায়োসিকিউরিটি ও পুষ্টিকর খাদ্য নিয়ন্ত্রিত খামার।',
    image: APP_IMAGES.sectorPoultry,
    managerUserId: 'user-admin',
    managerName: 'Engr. Kazi Tariqul Islam',
    status: 'active',
    establishedDate: '2024-12-15',
    totalArea: '8 Bighas / ২.৫ একর',
    customMetrics: [
      { label: 'Total Chickens', labelBn: 'মোট মুরগির সংখ্যা', value: 6200, unit: 'Birds / টি' },
      { label: 'Mature Birds', labelBn: 'পরিপক্ব সোনালী মুরগি', value: 4500, unit: 'Birds / টি' },
      { label: 'Daily Egg Production', labelBn: 'দৈনিক ডিম সংগ্রহ', value: 3400, unit: 'Eggs / টি' },
      { label: 'Mortality Rate', labelBn: 'মৃত্যুহার', value: 0.8, unit: '%' },
    ],
  },
  {
    id: 'sec-goat',
    code: 'GOAT-03',
    name: 'Goat Farming',
    nameBn: 'ব্ল্যাক বেঙ্গল ছাগল খামার',
    description: 'Pedigree Black Bengal and Jamunapari goat breeding and fattening on elevated slotted wooden floors in Chuadanga.',
    descriptionBn: 'চুয়াডাঙ্গায় মাচা পদ্ধতিতে খাঁটি ব্ল্যাক বেঙ্গল ও যমুনাপারি ছাগলের বৈজ্ঞানিক প্রজনন ও হৃষ্টপুষ্টকরণ খামার।',
    image: APP_IMAGES.sectorGoat,
    managerUserId: 'user-mgr-goat',
    managerName: 'Abul Kashem',
    status: 'active',
    establishedDate: '2025-01-05',
    totalArea: '5 Bighas / ১.৬ একর',
    customMetrics: [
      { label: 'Total Goats', labelBn: 'মোট ছাগলের সংখ্যা', value: 148, unit: 'Goats / টি' },
      { label: 'Breeding Does (Female)', labelBn: 'প্রজননক্ষম মাদী ছাগল', value: 85, unit: 'Does / টি' },
      { label: 'Kids Born This Season', labelBn: 'চলতি মৌসুমে জন্ম নেওয়া বাচ্চা', value: 42, unit: 'Kids / টি' },
      { label: 'Breeding Bucks (Male)', labelBn: 'খাঁটি প্রজনন পাঁঠা', value: 12, unit: 'Bucks / টি' },
    ],
  },
  {
    id: 'sec-pigeon',
    code: 'PIGEON-04',
    name: 'Pigeon Farming',
    nameBn: 'উন্নত জাতের কবুতর খামার',
    description: 'Commercial exotic and squab-producing pigeon breeding including King, Strasser, Siraji and high-flying breeds.',
    descriptionBn: 'কিং, সিরাজি ও উন্নত জাতের ব্রুডিং কবুতর পালন ও স্কোয়াব (বাচ্চা) বাণিজ্যিক বিপণন প্রকল্প।',
    image: APP_IMAGES.hero,
    managerUserId: 'user-admin',
    managerName: 'Engr. Kazi Tariqul Islam',
    status: 'active',
    establishedDate: '2025-02-01',
    totalArea: '2 Bighas',
    customMetrics: [
      { label: 'Breeding Pairs', labelBn: 'মোট জোড়া কবুতর', value: 480, unit: 'Pairs / জোড়া' },
      { label: 'Active Chicks (Squabs)', labelBn: 'চলতি বাচ্চা', value: 210, unit: 'Squabs / টি' },
      { label: 'Monthly Sold Pairs', labelBn: 'মাসিক বিক্রয়কৃত জোড়া', value: 140, unit: 'Pairs / জোড়া' },
      { label: 'Fertility Rate', labelBn: 'উর্বরতা হার', value: 92, unit: '%' },
    ],
  },
  {
    id: 'sec-veg',
    code: 'VEG-05',
    name: 'Vegetable Cultivation',
    nameBn: 'জৈব শাকসবজি চাষ',
    description: 'Year-round pesticide-safe vegetables using drip irrigation, mulching paper, and bio-fertilizer in Narsingdi fertile belt.',
    descriptionBn: 'নরসিংদীতে মালচিং পেপার, ট্রিপল ট্রেলিস ও ড্রিপ সেচ পদ্ধতিতে বিষমুক্ত বারোমাসি লাউ, পটল, ক্যাপসিকাম ও টমেটো চাষ।',
    image: APP_IMAGES.sectorVegetable,
    managerUserId: 'user-admin',
    managerName: 'Engr. Kazi Tariqul Islam',
    status: 'active',
    establishedDate: '2024-10-01',
    totalArea: '18 Bighas / ৬ একর',
    customMetrics: [
      { label: 'Cultivated Area', labelBn: 'আবাদকৃত জমির পরিমাণ', value: 18, unit: 'Bighas / বিঘা' },
      { label: 'Primary Crops', labelBn: 'প্রধান ফসল', value: 'Tomato, Gourd, Pointed Gourd', unit: 'Crops' },
      { label: 'Weekly Harvest Yield', labelBn: 'সাপ্তাহিক উত্তোলন', value: 3400, unit: 'Kg / কেজি' },
      { label: 'Current Wholesale Price', labelBn: 'গড় পাইকারি মূল্য', value: 38, unit: '৳ / Kg' },
    ],
  },
];

export const initialInvestments: Investment[] = [
  {
    id: 'inv-rec-1',
    investorId: 'inv-1', // Kazi Rafiqul Islam
    sectorId: 'sec-duck',
    amount: 800000, // ৳ 8,00,000
    date: '2025-01-15',
    paymentMethod: 'Bank Transfer',
    transactionRef: 'IBBL-NPSB-98712345',
    ownershipPercentage: 20.0,
    calculationType: 'net_profit_percentage',
    status: 'active',
    notes: '20% profit share on net earnings of Duck Farming sector.',
  },
  {
    id: 'inv-rec-2',
    investorId: 'inv-1', // Kazi Rafiqul Islam
    sectorId: 'sec-goat',
    amount: 500000, // ৳ 5,00,000
    date: '2025-02-01',
    paymentMethod: 'bKash',
    transactionRef: 'BK-TRX-874639201',
    ownershipPercentage: 25.0,
    calculationType: 'net_profit_percentage',
    status: 'active',
    notes: '25% equity in goat breeding and fattening batch #1.',
  },
  {
    id: 'inv-rec-3',
    investorId: 'inv-2', // Begum Farzana Ahmed
    sectorId: 'sec-veg',
    amount: 1000000, // ৳ 10,00,000
    date: '2025-03-20',
    paymentMethod: 'Bank Transfer',
    transactionRef: 'SCB-BEFTN-20250320',
    ownershipPercentage: 30.0,
    calculationType: 'net_profit_percentage',
    status: 'active',
    notes: '30% profit share in organic vegetable cultivation & Karwan Bazar bulk sales.',
  },
  {
    id: 'inv-rec-4',
    investorId: 'inv-3', // Dr. Mahmud Hasan
    sectorId: 'sec-poultry',
    amount: 600000, // ৳ 6,00,000
    date: '2025-05-10',
    paymentMethod: 'Bank Transfer',
    transactionRef: 'CBL-RTGS-55443322',
    ownershipPercentage: 15.0,
    calculationType: 'net_profit_percentage',
    status: 'active',
    notes: '15% ownership in Gazipur Poultry shed expansion.',
  },
  {
    id: 'inv-rec-5',
    investorId: 'inv-4', // Tanvir Hossain
    sectorId: 'sec-pigeon',
    amount: 400000, // ৳ 4,00,000
    date: '2025-06-25',
    paymentMethod: 'Nagad',
    transactionRef: 'NG-TX-99881122',
    ownershipPercentage: 22.0,
    calculationType: 'net_profit_percentage',
    status: 'active',
    notes: '22% profit share in fancy and squab pigeon farm.',
  },
];

export const initialIncomes: IncomeRecord[] = [
  {
    id: 'inc-01',
    date: '2026-09-01',
    sectorId: 'sec-duck',
    category: 'Sale of Duck Eggs',
    categoryBn: 'হাঁসের ডিম বিক্রয়',
    product: 'Fresh Organic Duck Eggs (হাঁসের লাল ডিম)',
    quantity: 18000,
    unit: 'Pieces',
    unitPrice: 12.5,
    totalAmount: 225000,
    customerBuyer: 'Karwan Bazar Egg Wholesalers Union, Dhaka',
    paymentMethod: 'Bank Transfer',
    invoiceNo: 'INV-DUCK-2026-001',
    addedByUserId: 'user-accountant',
    addedByName: 'Md. Mizanur Rahman, FCA',
    status: 'approved',
  },
  {
    id: 'inc-02',
    date: '2026-09-05',
    sectorId: 'sec-duck',
    category: 'Sale of Mature Ducks',
    categoryBn: 'পরিপক্ব হাঁস বিক্রয়',
    product: 'Khaki Campbell Live Ducks for meat',
    quantity: 320,
    unit: 'Birds',
    unitPrice: 480,
    totalAmount: 153600,
    customerBuyer: 'Bhairab Wholesale Live Bird Depot',
    paymentMethod: 'Cash',
    invoiceNo: 'INV-DUCK-2026-002',
    addedByUserId: 'user-accountant',
    status: 'approved',
  },
  {
    id: 'inc-03',
    date: '2026-09-08',
    sectorId: 'sec-poultry',
    category: 'Sale of Broiler / Sonali Chickens',
    categoryBn: 'সোনালী মুরগি পাইকারি বিক্রয়',
    product: 'Dressed & Live Sonali Chickens',
    quantity: 1200,
    unit: 'Kg',
    unitPrice: 285,
    totalAmount: 342000,
    customerBuyer: 'Kaptan Bazar Broiler Merchants, Dhaka',
    paymentMethod: 'Bank Transfer',
    invoiceNo: 'INV-POULTRY-2026-01',
    addedByUserId: 'user-accountant',
    status: 'approved',
  },
  {
    id: 'inc-04',
    date: '2026-09-12',
    sectorId: 'sec-poultry',
    category: 'Sale of Layer Eggs',
    categoryBn: 'লেয়ার মুরগির ডিম বিক্রয়',
    product: 'Brown Table Eggs Grade A',
    quantity: 24000,
    unit: 'Pieces',
    unitPrice: 11.5,
    totalAmount: 276000,
    customerBuyer: 'Shwapno Super Shop Regional Supply',
    paymentMethod: 'Bank Transfer',
    invoiceNo: 'INV-POULTRY-2026-02',
    addedByUserId: 'user-accountant',
    status: 'approved',
  },
  {
    id: 'inc-05',
    date: '2026-09-14',
    sectorId: 'sec-goat',
    category: 'Sale of Goats',
    categoryBn: 'ব্ল্যাক বেঙ্গল খাঁটি ছাগল ও পাঁঠা বিক্রয়',
    product: 'Black Bengal Breeding Bucks & Fattened Goats',
    quantity: 14,
    unit: 'Heads',
    unitPrice: 14500,
    totalAmount: 203000,
    customerBuyer: 'Regional Breeders Association & Gabtoli Livestock Market',
    paymentMethod: 'Bank Transfer',
    invoiceNo: 'INV-GOAT-2026-01',
    addedByUserId: 'user-accountant',
    status: 'approved',
  },
  {
    id: 'inc-06',
    date: '2026-09-17',
    sectorId: 'sec-pigeon',
    category: 'Sale of Pigeons & Squabs',
    categoryBn: 'কবুতরের বাচ্চা (স্কোয়াব) ও জোড়া বিক্রয়',
    product: 'King & Siraji Fancy Pigeon Pairs',
    quantity: 45,
    unit: 'Pairs',
    unitPrice: 2800,
    totalAmount: 126000,
    customerBuyer: 'Mirpur Pigeon Market & Hobbyist Breeders',
    paymentMethod: 'bKash',
    invoiceNo: 'INV-PIGEON-2026-01',
    addedByUserId: 'user-accountant',
    status: 'approved',
  },
  {
    id: 'inc-07',
    date: '2026-09-19',
    sectorId: 'sec-veg',
    category: 'Sale of Vegetables',
    categoryBn: 'জৈব লাউ ও টমেটো পাইকারি বিক্রয়',
    product: 'Organic Bottle Gourd (লাউ) & Fresh Tomatoes',
    quantity: 7500,
    unit: 'Kg',
    unitPrice: 42,
    totalAmount: 315000,
    customerBuyer: 'Jatrabari & Karwan Bazar Wholesale Arat, Dhaka',
    paymentMethod: 'Bank Transfer',
    invoiceNo: 'INV-VEG-2026-01',
    addedByUserId: 'user-accountant',
    status: 'approved',
  },
  {
    id: 'inc-08',
    date: '2026-09-21',
    sectorId: 'sec-veg',
    category: 'Sale of Vegetables',
    categoryBn: 'পটল ও করলা চালান বিক্রয়',
    product: 'Pointed Gourd (পটল) & Bitter Gourd (করলা)',
    quantity: 3200,
    unit: 'Kg',
    unitPrice: 48,
    totalAmount: 153600,
    customerBuyer: 'Agora & Unimart Fresh Agro Suppliers',
    paymentMethod: 'bKash',
    invoiceNo: 'INV-VEG-2026-02',
    addedByUserId: 'user-accountant',
    status: 'approved',
  },
];

export const initialExpenses: ExpenseRecord[] = [
  {
    id: 'exp-01',
    date: '2026-09-02',
    sectorId: 'sec-duck',
    category: 'Feed',
    categoryBn: 'খাদ্য ক্রয় (হাঁস ফিড)',
    description: 'CP Duck Feed Grower & Layer mash (80 bags x 50kg)',
    amount: 156000,
    vendor: 'CP Bangladesh Ltd.',
    paymentMethod: 'Bank Transfer',
    voucherNo: 'VOUCH-DUCK-001',
    addedByUserId: 'user-mgr-duck',
    addedByName: 'Md. Jahangir Alam',
    status: 'approved',
    approvedByUserId: 'user-accountant',
    approvedByName: 'Md. Mizanur Rahman, FCA',
    approvedAt: '2026-09-02',
  },
  {
    id: 'exp-02',
    date: '2026-09-06',
    sectorId: 'sec-duck',
    category: 'Medicine & Vaccines',
    categoryBn: 'ওষুধ ও ডাক প্লেগ ভ্যাকসিন',
    description: 'Duck Plague vaccines, Liver tonic, and mineral electrolyte premix',
    amount: 18500,
    vendor: 'Renata Animal Health Ltd.',
    paymentMethod: 'bKash',
    voucherNo: 'VOUCH-DUCK-002',
    addedByUserId: 'user-mgr-duck',
    status: 'approved',
    approvedByUserId: 'user-accountant',
    approvedAt: '2026-09-07',
  },
  {
    id: 'exp-03',
    date: '2026-09-07',
    sectorId: 'sec-duck',
    category: 'Labor',
    categoryBn: 'খামার শ্রমিকদের মাসিক মজুরি',
    description: 'Monthly wages for 4 full-time duck farm caretakers and egg collectors',
    amount: 52000,
    vendor: 'Farm Staff Payroll',
    paymentMethod: 'Cash',
    voucherNo: 'VOUCH-DUCK-003',
    addedByUserId: 'user-mgr-duck',
    status: 'approved',
    approvedByUserId: 'user-admin',
    approvedAt: '2026-09-08',
  },
  {
    id: 'exp-04',
    date: '2026-09-03',
    sectorId: 'sec-poultry',
    category: 'Feed',
    categoryBn: 'পোল্ট্রি ফিড ক্রয়',
    description: 'Provita Layer Pellets (120 bags x 50kg)',
    amount: 228000,
    vendor: 'Provita Feed Mills Ltd.',
    paymentMethod: 'Bank Transfer',
    voucherNo: 'VOUCH-POULTRY-01',
    addedByUserId: 'user-accountant',
    status: 'approved',
    approvedByUserId: 'user-admin',
    approvedAt: '2026-09-04',
  },
  {
    id: 'exp-05',
    date: '2026-09-10',
    sectorId: 'sec-poultry',
    category: 'Electricity & Gas',
    categoryBn: 'বিদ্যুৎ ও ব্রুডিং খরচ',
    description: 'REB Electricity bill for Gazipur poultry sheds + solar backup maintenance',
    amount: 28400,
    vendor: 'Dhaka Palli Bidyut Samity-1',
    paymentMethod: 'bKash',
    voucherNo: 'VOUCH-POULTRY-02',
    addedByUserId: 'user-accountant',
    status: 'approved',
    approvedByUserId: 'user-accountant',
    approvedAt: '2026-09-11',
  },
  {
    id: 'exp-06',
    date: '2026-09-04',
    sectorId: 'sec-goat',
    category: 'Feed',
    categoryBn: 'নেপিয়ার ঘাস ও দানাদার খাদ্য',
    description: 'High-protein goat pellets, wheat bran, molasses & Napier grass bundle cutting',
    amount: 48500,
    vendor: 'Aftab Feed Products',
    paymentMethod: 'Cash',
    voucherNo: 'VOUCH-GOAT-01',
    addedByUserId: 'user-mgr-goat',
    addedByName: 'Abul Kashem',
    status: 'approved',
    approvedByUserId: 'user-accountant',
    approvedAt: '2026-09-05',
  },
  {
    id: 'exp-07',
    date: '2026-09-12',
    sectorId: 'sec-goat',
    category: 'Vaccination & Vet Care',
    categoryBn: 'পিপিআর ভ্যাকসিন ও ডিওয়ার্মিং',
    description: 'PPR vaccination, Enterotoxemia boosters, and local vet visit honorarium',
    amount: 14200,
    vendor: 'Chuadanga Upazila Livestock Vet Service',
    paymentMethod: 'Cash',
    voucherNo: 'VOUCH-GOAT-02',
    addedByUserId: 'user-mgr-goat',
    status: 'approved',
    approvedByUserId: 'user-accountant',
    approvedAt: '2026-09-13',
  },
  {
    id: 'exp-08',
    date: '2026-09-05',
    sectorId: 'sec-pigeon',
    category: 'Feed',
    categoryBn: 'কবুতরের মিক্স দানাদার শস্য',
    description: 'Mix grains (wheat, corn, green peas, safflower, mustard seeds)',
    amount: 32000,
    vendor: 'Khatunganj Agro Commodity Traders',
    paymentMethod: 'bKash',
    voucherNo: 'VOUCH-PIGEON-01',
    addedByUserId: 'user-accountant',
    status: 'approved',
    approvedByUserId: 'user-admin',
    approvedAt: '2026-09-06',
  },
  {
    id: 'exp-09',
    date: '2026-09-08',
    sectorId: 'sec-veg',
    category: 'Fertilizer & Organic Manure',
    categoryBn: 'জৈব সার ও ভার্মিকম্পোস্ট',
    description: 'Vermicompost (কেঁচো সার), Trichoderma bio-fungicide, and organic potash',
    amount: 46000,
    vendor: 'ACI Agribusiness Ltd.',
    paymentMethod: 'Bank Transfer',
    voucherNo: 'VOUCH-VEG-01',
    addedByUserId: 'user-accountant',
    status: 'approved',
    approvedByUserId: 'user-admin',
    approvedAt: '2026-09-09',
  },
  {
    id: 'exp-10',
    date: '2026-09-15',
    sectorId: 'sec-veg',
    category: 'Labor & Trellis Repair',
    categoryBn: 'মাচা মেরামত ও ফসল সংগ্রহ মজুরি',
    description: 'Bamboo replacement for vegetable trellis + harvest labor team (10 days)',
    amount: 41000,
    vendor: 'Local Farm Labor Group',
    paymentMethod: 'Cash',
    voucherNo: 'VOUCH-VEG-02',
    addedByUserId: 'user-accountant',
    status: 'approved',
    approvedByUserId: 'user-accountant',
    approvedAt: '2026-09-16',
  },
  {
    id: 'exp-11',
    date: '2026-09-22',
    sectorId: 'sec-duck',
    category: 'Water System & Pond Cleaning',
    categoryBn: 'পুকুর সংস্কার ও পানির লাইন মেরামত',
    description: 'Deep tube-well pump overhaul and bio-secure pond netting extension',
    amount: 15000,
    vendor: 'Bhai Bhai Electric & Engineering Works',
    paymentMethod: 'bKash',
    voucherNo: 'VOUCH-DUCK-004',
    addedByUserId: 'user-mgr-duck',
    status: 'pending_approval', // Testing approval workflow!
  },
  {
    id: 'exp-12',
    date: '2026-09-22',
    sectorId: 'sec-goat',
    category: 'Equipment',
    categoryBn: 'ছাগলের কাঠের মাচা সম্প্রসারণ',
    description: 'Treated Garjan wood slatted floor panels for 20 new goat kids',
    amount: 22000,
    vendor: 'Chuadanga Wood Mills',
    paymentMethod: 'Cash',
    voucherNo: 'VOUCH-GOAT-03',
    addedByUserId: 'user-mgr-goat',
    status: 'pending_approval', // Testing approval workflow!
  },
];

export const initialOperations: FarmOperationRecord[] = [
  {
    id: 'op-01',
    date: '2026-09-20',
    sectorId: 'sec-duck',
    animalCount: 3850,
    mortalityCount: 1,
    feedConsumedKg: 460,
    medicineUsed: 'Electrolyte liquid and Vitamin AD3E in water trough',
    laborCount: 4,
    productionQty: 2780,
    productionUnit: 'Eggs',
    salesQty: 2500,
    incidentNotes: 'High water level normal after rain; water oxygenated via fountain.',
    reportedByUserId: 'user-mgr-duck',
    reportedByName: 'Md. Jahangir Alam',
  },
  {
    id: 'op-02',
    date: '2026-09-21',
    sectorId: 'sec-duck',
    animalCount: 3849,
    mortalityCount: 0,
    feedConsumedKg: 465,
    medicineUsed: 'None',
    laborCount: 4,
    productionQty: 2810,
    productionUnit: 'Eggs',
    salesQty: 2800,
    incidentNotes: 'All flocks energetic; laying rate holding at 89.5%.',
    reportedByUserId: 'user-mgr-duck',
    reportedByName: 'Md. Jahangir Alam',
  },
  {
    id: 'op-03',
    date: '2026-09-21',
    sectorId: 'sec-goat',
    animalCount: 148,
    mortalityCount: 0,
    feedConsumedKg: 210,
    medicineUsed: 'De-worming Albendazole given to Batch B',
    laborCount: 3,
    productionQty: 0,
    productionUnit: 'Heads',
    incidentNotes: 'Two Black Bengal does confirmed pregnant by veterinary ultrasound.',
    reportedByUserId: 'user-mgr-goat',
    reportedByName: 'Abul Kashem',
  },
  {
    id: 'op-04',
    date: '2026-09-20',
    sectorId: 'sec-veg',
    animalCount: 0,
    mortalityCount: 0,
    feedConsumedKg: 0,
    laborCount: 8,
    productionQty: 1150,
    productionUnit: 'Kg (Tomatoes & Gourds)',
    salesQty: 1150,
    incidentNotes: 'No insect pests observed; yellow sticky traps and pheromone traps active.',
    reportedByUserId: 'user-admin',
    reportedByName: 'Engr. Kazi Tariqul Islam',
  },
];

export const initialInventory: InventoryItem[] = [
  {
    id: 'inv-item-1',
    sectorId: 'sec-duck',
    name: 'CP Duck Layer Pellet Feed (50kg Bag)',
    nameBn: 'সিপি হাঁস লেয়ার ফিড (৫০ কেজি বস্তা)',
    category: 'feed',
    currentStock: 45,
    unit: 'Bags',
    unitCost: 1950,
    minReorderLevel: 20,
    supplier: 'CP Bangladesh Ltd.',
    lastRestocked: '2026-09-02',
  },
  {
    id: 'inv-item-2',
    sectorId: 'sec-duck',
    name: 'Duck Plague Vaccine Ampoules',
    nameBn: 'ডাক প্লেগ ভ্যাকসিন অ্যাম্পুল',
    category: 'vaccine',
    currentStock: 12,
    unit: 'Vials (100 doses each)',
    unitCost: 450,
    minReorderLevel: 5,
    supplier: 'Renata Animal Health',
    lastRestocked: '2026-09-06',
  },
  {
    id: 'inv-item-3',
    sectorId: 'sec-poultry',
    name: 'Sonali Chicken Starter Feed (50kg)',
    nameBn: 'সোনালী স্টার্টার ফিড (৫০ কেজি)',
    category: 'feed',
    currentStock: 60,
    unit: 'Bags',
    unitCost: 2150,
    minReorderLevel: 25,
    supplier: 'Provita Feed Mills',
    lastRestocked: '2026-09-03',
  },
  {
    id: 'inv-item-4',
    sectorId: 'sec-veg',
    name: 'Trichoderma Bio-fertilizer (25kg)',
    nameBn: 'ট্রাইকোডার্মা জৈব সার (২৫ কেজি)',
    category: 'fertilizer',
    currentStock: 8,
    unit: 'Sacks',
    unitCost: 1200,
    minReorderLevel: 10, // Triggers low-stock notice!
    supplier: 'ACI Agribusiness Ltd.',
    lastRestocked: '2026-08-28',
  },
  {
    id: 'inv-item-5',
    sectorId: 'sec-veg',
    name: 'Egg Packaging Plastic Crates (30-egg tray)',
    nameBn: 'ডিম প্যাকিং প্লাস্টিক ট্রে',
    category: 'packaging',
    currentStock: 350,
    unit: 'Trays',
    unitCost: 45,
    minReorderLevel: 100,
    supplier: 'Bengal Plastics Ltd.',
    lastRestocked: '2026-09-10',
  },
];

export const initialAssets: AssetItem[] = [
  {
    id: 'asset-1',
    sectorId: 'sec-duck',
    name: 'Kishoreganj Haor Agro Land (Permanent Leasehold 12 Bighas)',
    nameBn: 'কিশোরগঞ্জ খামার জমি (১২ বিঘা স্থায়ী লিজ)',
    category: 'land',
    purchaseDate: '2024-09-15',
    purchaseValue: 2400000,
    currentValue: 2800000,
    location: 'Itna, Kishoreganj Haor Belt',
    responsiblePerson: 'Md. Jahangir Alam',
    status: 'operational',
  },
  {
    id: 'asset-2',
    sectorId: 'sec-duck',
    name: 'Solar-Powered Automated Water Circulation System',
    nameBn: 'সৌরচালিত স্বয়ংক্রিয় পানি সঞ্চালন পাম্প ও ফোয়ারা',
    category: 'solar',
    purchaseDate: '2024-11-20',
    purchaseValue: 350000,
    currentValue: 320000,
    location: 'Duck Pond Sector 1',
    responsiblePerson: 'Md. Jahangir Alam',
    status: 'operational',
  },
  {
    id: 'asset-3',
    sectorId: 'sec-poultry',
    name: 'Automated Ventilated Layer Shed (Steel Frame 5,000 Bird Capacity)',
    nameBn: 'অটোমেটেড লেয়ার শেড (ইস্পাত কাঠামো, ধারণক্ষমতা ৫,০০০ মুরগি)',
    category: 'shed',
    purchaseDate: '2024-12-01',
    purchaseValue: 1850000,
    currentValue: 1800000,
    location: 'Chandra, Gazipur',
    responsiblePerson: 'Engr. Kazi Tariqul Islam',
    status: 'operational',
  },
  {
    id: 'asset-4',
    sectorId: 'sec-goat',
    name: 'Elevated Slotted Wooden Goat House (3 Sheds)',
    nameBn: 'মাচা পদ্ধতিতে কাঠের আধুনিক ছাগল শেড (৩টি)',
    category: 'shed',
    purchaseDate: '2025-01-02',
    purchaseValue: 650000,
    currentValue: 620000,
    location: 'Damurhuda, Chuadanga',
    responsiblePerson: 'Abul Kashem',
    status: 'operational',
  },
  {
    id: 'asset-5',
    sectorId: 'sec-veg',
    name: 'Mahindra Agro Pickup Truck (1.5 Ton Transport)',
    nameBn: 'মাহিন্দ্রা এগ্রো পিকআপ ভ্যান (১.৫ টন শাকসবজি ও ডিম পরিবহন)',
    category: 'vehicle',
    purchaseDate: '2025-02-15',
    purchaseValue: 1450000,
    currentValue: 1350000,
    location: 'Dhaka-Gazipur Route',
    responsiblePerson: 'Transport In-charge',
    status: 'operational',
  },
];

export const initialDocuments: DocumentRecord[] = [
  {
    id: 'doc-01',
    title: 'Duck Farming Sector Mudaraba Investment Agreement #SB-2025-01',
    titleBn: 'হাঁস খামার প্রকল্প মুদারাবা বিনিয়োগ চুক্তিপত্র #এসবি-২০২৫-০১',
    category: 'agreement',
    investorId: 'inv-1',
    sectorId: 'sec-duck',
    date: '2025-01-15',
    fileSize: '2.4 MB',
    notes: 'Signed and notarized partnership deed with Kazi Rafiqul Islam.',
  },
  {
    id: 'doc-02',
    title: 'Goat Breeding Partnership Deed & Biosecurity Protocols',
    titleBn: 'ছাগল প্রজনন অংশীদারিত্ব চুক্তি ও বায়োসিকিউরিটি গাইডলাইন',
    category: 'agreement',
    investorId: 'inv-1',
    sectorId: 'sec-goat',
    date: '2025-02-01',
    fileSize: '1.8 MB',
    notes: '25% equity agreement for Chuadanga goat breeding facility.',
  },
  {
    id: 'doc-03',
    title: 'Vegetable Greenhouse Investment & Profit Deed #SB-2025-03',
    titleBn: 'গ্রিনহাউস সবজি প্রকল্প বিনিয়োগ চুক্তি #এসবি-২০২৫-০৩',
    category: 'agreement',
    investorId: 'inv-2',
    sectorId: 'sec-veg',
    date: '2025-03-20',
    fileSize: '3.1 MB',
    notes: 'NRB foreign remittance investment documentation for Begum Farzana Ahmed.',
  },
  {
    id: 'doc-04',
    title: 'Govt. Agro Trade License & Livestock Directorate Certification',
    titleBn: 'সরকারি ট্রেড লাইসেন্স ও প্রাণিসম্পদ অধিদপ্তর খামার নিবন্ধন সনদ',
    category: 'license',
    date: '2024-10-10',
    fileSize: '4.5 MB',
    notes: 'Verified commercial registration by Department of Livestock Services (DLS).',
  },
  {
    id: 'doc-05',
    title: 'Soil Nutrient & Water Bio-Purity Lab Report (BARI / SRDI)',
    titleBn: 'মাটি ও পানির গুণাগুণ ল্যাব টেস্ট রিপোর্ট (বারি / এসআরডিআই)',
    category: 'report',
    sectorId: 'sec-veg',
    date: '2025-02-28',
    fileSize: '1.2 MB',
    notes: 'Organic certification compliance test from Bangladesh Agricultural Research Institute.',
  },
];

export const initialProfitDistributions: ProfitDistribution[] = [
  {
    id: 'dist-01',
    investmentId: 'inv-rec-1',
    investorId: 'inv-1',
    sectorId: 'sec-duck',
    period: 'Q2 2026 (Apr - Jun)',
    sectorRevenue: 420000,
    sectorExpense: 260000,
    sectorNetProfit: 160000,
    investorOwnershipPercent: 20.0,
    investorShare: 32000,
    paidAmount: 32000,
    pendingAmount: 0,
    paymentDate: '2026-07-05',
    paymentMethod: 'Bank Transfer (IBBL)',
    paymentRef: 'DIV-2026-Q2-01',
    status: 'paid',
  },
  {
    id: 'dist-02',
    investmentId: 'inv-rec-2',
    investorId: 'inv-1',
    sectorId: 'sec-goat',
    period: 'Q2 2026 (Apr - Jun)',
    sectorRevenue: 280000,
    sectorExpense: 140000,
    sectorNetProfit: 140000,
    investorOwnershipPercent: 25.0,
    investorShare: 35000,
    paidAmount: 35000,
    pendingAmount: 0,
    paymentDate: '2026-07-05',
    paymentMethod: 'bKash Merchant Disburse',
    paymentRef: 'DIV-2026-Q2-02',
    status: 'paid',
  },
  {
    id: 'dist-03',
    investmentId: 'inv-rec-3',
    investorId: 'inv-2',
    sectorId: 'sec-veg',
    period: 'Q2 2026 (Apr - Jun)',
    sectorRevenue: 510000,
    sectorExpense: 230000,
    sectorNetProfit: 280000,
    investorOwnershipPercent: 30.0,
    investorShare: 84000,
    paidAmount: 84000,
    pendingAmount: 0,
    paymentDate: '2026-07-08',
    paymentMethod: 'Bank Transfer (SCB)',
    paymentRef: 'DIV-2026-Q2-03',
    status: 'paid',
  },
];

export const initialAuditLogs: AuditLog[] = [
  {
    id: 'audit-01',
    timestamp: '2026-09-01 10:30 AM',
    userId: 'user-accountant',
    userName: 'Md. Mizanur Rahman, FCA',
    role: 'accountant',
    action: 'RECORD_INCOME',
    sectorId: 'sec-duck',
    details: 'Recorded sale of 18,000 duck eggs for ৳2,25,000 (Invoice: INV-DUCK-2026-001)',
  },
  {
    id: 'audit-02',
    timestamp: '2026-09-02 02:15 PM',
    userId: 'user-accountant',
    userName: 'Md. Mizanur Rahman, FCA',
    role: 'accountant',
    action: 'APPROVE_EXPENSE',
    sectorId: 'sec-duck',
    details: 'Approved CP Duck Feed purchase expense voucher ৳1,56,000',
    prevValue: 'Status: pending_approval',
    newValue: 'Status: approved',
  },
  {
    id: 'audit-03',
    timestamp: '2026-09-14 11:45 AM',
    userId: 'user-admin',
    userName: 'Engr. Kazi Tariqul Islam',
    role: 'super_admin',
    action: 'UPDATE_SECTOR_METRIC',
    sectorId: 'sec-goat',
    details: 'Updated breeding kids born count to 42 heads after successful births',
  },
  {
    id: 'audit-04',
    timestamp: '2026-09-21 09:20 AM',
    userId: 'user-mgr-duck',
    userName: 'Md. Jahangir Alam',
    role: 'sector_manager',
    action: 'LOG_DAILY_OPERATION',
    sectorId: 'sec-duck',
    details: 'Logged daily egg production count: 2,810 eggs, 0 mortality',
  },
];

export const initialAnnouncements: Announcement[] = [
  {
    id: 'ann-1',
    title: 'Duck Egg Production Reaches Record 89.5% Laying Capacity',
    titleBn: 'হাঁস খামারে ডিম উৎপাদনের হার রেকর্ড ৮৯.৫% এ উন্নীত',
    content: 'Through our new bio-secure freshwater channels and high-protein feed mix, the Haor duck farm has crossed 2,800 eggs daily output.',
    contentBn: 'কিশোরগঞ্জ মুক্ত জলাশয়ে নতুন ভাসমান খাদ্য ও বায়োসিকিউরিটি জোরদারের ফলে দৈনিক ডিম সংগ্রহ ২,৮০০ ছাড়িয়ে নতুন মাইলফলক ছুঁয়েছে।',
    sectorId: 'sec-duck',
    priority: 'important',
    targetAudience: 'all',
    date: '2026-09-20',
  },
  {
    id: 'ann-2',
    title: 'Quarterly Investor Farm Visit & Annual Financial Briefing',
    titleBn: 'ত্রৈমাসিক বিনিয়োগকারী খামার পরিদর্শন ও বার্ষিক আর্থিক সভা',
    content: 'All verified investors are invited to our Gazipur and Savar agro facilities for on-ground project inspection and luncheon on October 15, 2026.',
    contentBn: 'আগামী ১৫ অক্টোবর ২০২৬ তারিখে সকল সম্মানিত বিনিয়োগকারীদের গাজীপুর খামার পরিদর্শন, সরাসরি অডিট পর্যালোচনা ও মধ্যাহ্নভোজে আমন্ত্রণ।',
    priority: 'normal',
    targetAudience: 'investors_only',
    date: '2026-09-18',
  },
  {
    id: 'ann-3',
    title: 'New Organic Drip Irrigation Lines Commissioned in Narsingdi',
    titleBn: 'নরসিংদী সবজি খামারে নতুন আধুনিক ড্রিপ সেচ লাইন চালু',
    content: '18 Bighas of high-value gourds and tomatoes now feature automated Israeli-standard drip irrigation, saving 60% water and fertilizer cost.',
    contentBn: '১৮ বিঘা সবজি প্রকল্পে অটোমেটেড ড্রিপ সেচ ব্যবস্থার কাজ সম্পন্ন হয়েছে, যা সার ও সেচ খরচ উল্লেখযোগ্যভাবে কমিয়েছে।',
    sectorId: 'sec-veg',
    priority: 'normal',
    targetAudience: 'all',
    date: '2026-09-12',
  },
];

export const initialGallery: GalleryItem[] = [
  {
    id: 'gal-1',
    sectorId: 'sec-duck',
    title: 'Healthy Khaki Campbell Flock in Bio-secure Pond',
    titleBn: 'হাওরের মুক্ত জলাশয়ে খাকি ক্যাম্পবেল হাঁসের ঝাঁক',
    description: 'Clean swimming waters in Kishoreganj Haor shelter.',
    mediaType: 'photo',
    url: APP_IMAGES.sectorDuck,
    date: '2026-09-18',
  },
  {
    id: 'gal-2',
    sectorId: 'sec-goat',
    title: 'Pedigree Black Bengal Does and Kids on Slatted Floor',
    titleBn: 'চুয়াডাঙ্গায় মাচায় লালিত খাঁটি ব্ল্যাক বেঙ্গল ছাগল',
    description: 'Elevated hygienic wooden slats preventing hoof rot and pneumonia.',
    mediaType: 'photo',
    url: APP_IMAGES.sectorGoat,
    date: '2026-09-15',
  },
  {
    id: 'gal-3',
    sectorId: 'sec-veg',
    title: 'Heavy Yield of Organic Bottle Gourds on Bamboo Trellis',
    titleBn: 'বাঁশের মাচায় বিষমুক্ত তাজা লাউয়ের বাম্পার ফলন',
    description: 'Pesticide-free organic vegetables ready for early morning harvest.',
    mediaType: 'photo',
    url: APP_IMAGES.sectorVegetable,
    date: '2026-09-19',
  },
  {
    id: 'gal-4',
    sectorId: 'sec-poultry',
    title: 'Automated Layer Shed with Solar Ventilation',
    titleBn: 'গাজীপুরে সোলার ভেন্টিলেটেড আধুনিক পোল্ট্রি শেড',
    description: 'Automated drinking nipples and climate sensor lines.',
    mediaType: 'photo',
    url: APP_IMAGES.sectorPoultry,
    date: '2026-09-10',
  },
];

export const initialCustomModules: CustomModule[] = [
  {
    id: 'mod-fish',
    name: 'Fish Farming (Pisciculture)',
    nameBn: 'মাছ চাষ প্রকল্প (বায়োফ্লক ও পুকুর)',
    slug: 'fish-farming',
    description: 'High-density commercial carp, Tilapia, and Shing-Magur fish production in controlled freshwater ponds.',
    iconName: 'Fish',
    createdAt: '2026-08-10',
    fields: [
      { id: 'f1', name: 'Pond Number', nameBn: 'পুকুর নং / ইউনিট', type: 'text', required: true },
      { id: 'f2', name: 'Fish Species', nameBn: 'মাছের প্রজাতি', type: 'dropdown', options: ['Rui/Katla (রুই/কাতলা)', 'Monosex Tilapia (তেলাপিয়া)', 'Pangas (পাঙ্গাশ)', 'Shing/Magur (শিং/মাগুর)'], required: true },
      { id: 'f3', name: 'Fingerlings Stocked', nameBn: 'মজুদ পোনার সংখ্যা', type: 'number', required: true },
      { id: 'f4', name: 'Average Weight (Gram)', nameBn: 'গড় ওজন (গ্রাম)', type: 'number', required: true },
      { id: 'f5', name: 'Feed Used (Kg)', nameBn: 'খাদ্য প্রয়োগ (কেজি)', type: 'number', required: false },
      { id: 'f6', name: 'Water Dissolved Oxygen (mg/L)', nameBn: 'পানিতে দ্রবীভূত অক্সিজেন', type: 'text', required: false },
    ],
    records: [
      {
        id: 'rec-fish-1',
        f1: 'Pond A-1 (Main Haor Canal)',
        f2: 'Monosex Tilapia (তেলাপিয়া)',
        f3: 25000,
        f4: 380,
        f5: 180,
        f6: '6.2 mg/L',
      },
      {
        id: 'rec-fish-2',
        f1: 'Pond B-2 (Nursery Unit)',
        f2: 'Rui/Katla (রুই/কাতলা)',
        f3: 15000,
        f4: 210,
        f5: 110,
        f6: '6.8 mg/L',
      },
    ],
  },
];

export const initialWidgets: DashboardWidgetConfig[] = [
  {
    id: 'w-kpis',
    key: 'kpi_cards',
    title: 'Financial & Operational Key Indicators',
    titleBn: 'আর্থিক ও পরিচালনা মূল নির্দেশক (KPIs)',
    visible: true,
    order: 1,
    colSpan: 'full',
    roleVisibility: ['super_admin', 'admin_manager', 'accountant', 'sector_manager'],
  },
  {
    id: 'w-charts-revenue',
    key: 'financial_trend_chart',
    title: 'Monthly Revenue, Expenses & Net Profit Trend',
    titleBn: 'মাসিক রাজস্ব, খরচ ও নিট লাভের ধারা',
    visible: true,
    order: 2,
    colSpan: 'half',
    roleVisibility: ['super_admin', 'admin_manager', 'accountant'],
  },
  {
    id: 'w-sector-pie',
    key: 'sector_distribution_chart',
    title: 'Sector-wise Revenue Contribution',
    titleBn: 'সেক্টরভিত্তিক রাজস্ব অবদান বিশ্লেষণ',
    visible: true,
    order: 3,
    colSpan: 'half',
    roleVisibility: ['super_admin', 'admin_manager', 'accountant'],
  },
  {
    id: 'w-recent-transactions',
    key: 'recent_transactions_table',
    title: 'Recent Verified Incomes & Expenses',
    titleBn: 'সাম্প্রতিক যাচাইকৃত আয় ও ব্যয়ের খতিয়ান',
    visible: true,
    order: 4,
    colSpan: 'full',
    roleVisibility: ['super_admin', 'admin_manager', 'accountant'],
  },
  {
    id: 'w-announcements',
    key: 'announcements_widget',
    title: 'Farm Field Notices & Live Operations Feed',
    titleBn: 'খামারের গুরুত্বপূর্ণ ঘোষণা ও আপডেট',
    visible: true,
    order: 5,
    colSpan: 'full',
    roleVisibility: ['super_admin', 'admin_manager', 'accountant', 'sector_manager', 'investor'],
  },
];

export const initialSettings: FarmSettings = {
  farmName: 'Ahmadun Agro',
  farmNameBn: 'আহমাদুন এগ্রো',
  tagline: 'Modern, Sustainable & Transparent Agro Investment in Bangladesh',
  taglineBn: 'বাংলাদেশে আধুনিক, টেকসই ও শতভাগ স্বচ্ছ সমন্বিত কৃষি বিনিয়োগ',
  logoText: 'AHMADUN AGRO',
  phone: '+880 1711-000111 / +880 1819-222333',
  email: 'contact@ahmadunagro.com',
  address: 'Chandra, Kaliakair, Gazipur & Gulshan-1, Dhaka',
  contactPhone: '+880 1711-000111 / +880 1819-222333',
  contactEmail: 'contact@ahmadunagro.com',
  farmAddress: 'Chandra, Kaliakair, Gazipur & Kishoreganj Haor Belt',
  farmAddressBn: 'চন্দ্রা, কালিয়াকৈর, গাজীপুর এবং কিশোরগঞ্জ হাওর অঞ্চল',
  officeAddress: 'Green Heritage Tower (Level 6), Plot 14, Gulshan-1, Dhaka-1212',
  officeAddressBn: 'গ্রীন হেরিটেজ টাওয়ার (লেভেল ৬), প্লট ১৪, গুলশান-১, ঢাকা-১২১২',
  bkashMerchant: '01711-987654',
  nagadMerchant: '01811-123456',
  bankName: 'Islami Bank Bangladesh PLC',
  bankAccount: '2050 3481 9002 4412',
  bankRouting: '125271890',
  currency: 'BDT',
  currencySymbol: '৳',
  bnNumberFormat: true,
  defaultLanguage: 'bn',
  themeColor: '#15803d', // Tailwind green-700
  approvalRequiredForExpenses: true,
  minExpenseApprovalLimit: 10000,
};
